### ISSUE TITLE
Module not found: Can't resolve './__generated__/CreatePageViewerQuery.graphql' in 'quickstart-with-relay-modern/src/components'

### ISSUE THREAD

**Issue by niieani** [graphcool/console#1278]
**bug**  

```
Time to run an example...

You've successfully set up your GraphQL backend. It's now time to test it. 
We've already prepared an Instagram example project for you.
Select your preferred technology:
```

Selected "React+Relay"

Downloaded .zip.

Running `npm` and `npm start`

**What is the current behavior?**

Getting an error message after running:

```
Failed to compile
./src/components/CreatePage.js
Module not found: Can't resolve './__generated__/CreatePageViewerQuery.graphql' in 'quickstart-with-relay-modern/src/components'
This error occurred during the build time and cannot be dismissed.
```

**What is the expected behavior?**

No idea, since I don't know what the next step was supposed to be. It shouldn't error.

**Comment by marktani** [comment]
Thanks for the report! Could you run this instead:

```sh
yarn install
yarn relay # invoke relay compiler
yarn start # open http://localhost:3000 in your browser
```
?

The instructions should be updated.

**Comment by timsuchanek** [comment]
@niieani The correct instructions like @marktani noted will be deployed in about 10min. Thanks for the heads up!

**Comment by niieani** [comment]
`yarn relay` fails:

```
yarn relay
yarn relay v0.27.5
$ relay-compiler --src ./src --schema ./schema.graphql
HINT: pass --watch to keep watching for changes.
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 1.
```

**Comment by niieani** [comment]
I've installed `watchman` globally via `yarn global add watchman`, but it still fails with a different error (I guess wrong version?)

```
yarn relay
yarn relay v0.27.5
$ relay-compiler --src ./src --schema ./schema.graphql
HINT: pass --watch to keep watching for changes.
ERROR: Unknown option --no-pretty

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= ERROR: Unknown option --no-pretty

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= ERROR: Unknown option --no-pretty

    at ChildProcess.<anonymous> (quickstart-with-relay-modern/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
```

**Comment by timsuchanek** [comment]
Unfortunately, Relay Modern needs watchman to run the relay-compiler, even not in watch mode.
I think the npm package watchman is unrelated to the watchman of facebook.

You can try installing it with `brew install watchman`

**Comment by niieani** [comment]
@timsuchanek I've installed `watchman` via brew, but still getting the same issue:

```
yarn relay
yarn relay v0.27.5
$ relay-compiler --src ./src --schema ./schema.graphql
HINT: pass --watch to keep watching for changes.
ERROR: Unknown option --no-pretty

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= ERROR: Unknown option --no-pretty

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= ERROR: Unknown option --no-pretty

    at ChildProcess.<anonymous> (quickstart-with-relay-modern/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
error Command failed with exit code 1.
```

I can confirm this is the brew-installed watchman:
```
which watchman
/usr/local/bin/watchman
```

**Comment by niieani** [comment]
Ok, I've solved the problem, I've accidentally installed fs-watchman into the repo. Works now!

**Comment by niieani** [comment]
I'll leave this open until the instructions regarding installing `watchman` are added.

**Comment by timsuchanek** [comment]
We should update the relay version in the example as then watchman is not needed anymore for normal compilation without --watch https://github.com/facebook/relay/commit/4f80e02205a05f05439a724c2620a80f2fd95737
