### ISSUE TITLE
Onboarding: Angular example is broken

### ISSUE THREAD

**Issue by sorenbs** [graphcool/console#368]
```
"/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
npm WARN unmet dependency /Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/node_modules/@angular-cli/ast-tools requires rxjs@'5.0.0-beta.11' but will load
npm WARN unmet dependency /Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/node_modules/rxjs,
npm WARN unmet dependency which is version 5.0.0-beta.12
npm WARN unmet dependency /Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/node_modules/@angular-cli/ast-tools requires typescript@'~2.0.3' but will load
npm WARN unmet dependency /Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/node_modules/typescript,
npm WARN unmet dependency which is version 1.9.0-dev.20160627-1.0
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/core@2.0.0-rc.6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.6 wants @angular/core@^2.0.0-rc.6
npm ERR! peerinvalid Peer @angular/compiler@2.0.0-rc.6 wants @angular/core@^2.0.0-rc.6
npm ERR! peerinvalid Peer @angular/forms@2.0.0-rc.6 wants @angular/core@^2.0.0-rc.6
npm ERR! peerinvalid Peer @angular/http@2.0.0-rc.6 wants @angular/core@^2.0.0-rc.6
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.6 wants @angular/core@^2.0.0-rc.6
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.6 wants @angular/core@^2.0.0-rc.6
npm ERR! peerinvalid Peer @angular/router@3.0.0-rc.2 wants @angular/core@^2.0.0-rc.6
npm ERR! peerinvalid Peer angular2-apollo@0.4.6 wants @angular/core@^2.0.0
npm ERR! peerinvalid Peer angular2-moment@1.0.0-beta.6 wants @angular/core@^2.0.0-rc.5

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sorenbs/Downloads/angular-apollo-instagram-example-master/npm-debug.log
sorenbs@Sorens-MBP ~/D/angular-apollo-instagram-example-master> npm start

> angular-apollo-instagram-example@ start /Users/sorenbs/Downloads/angular-apollo-instagram-example-master
> ng serve --port 3000

Error while running script "/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/addon/ng2/models/config/config.ts":
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/lib/bootstrap-local.js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/addon/ng2/models/config.ts:7:16)
    at Module._compile (module.js:409:26)
    at Object.require.extensions..ts (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/lib/bootstrap-local.js:30:14)
Error while running script "/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/addon/ng2/models/config.ts":
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/lib/bootstrap-local.js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/addon/ng2/models/config.ts:7:16)
    at Module._compile (module.js:409:26)
    at Object.require.extensions..ts (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/lib/bootstrap-local.js:30:14)
Unexpected token ...
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..ts (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/lib/bootstrap-local.js:30:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/addon/ng2/models/config.ts:7:16)
    at Module._compile (module.js:409:26)
    at Object.require.extensions..ts (/Users/sorenbs/Downloads/angular-apollo-instagram-example-master/node_modules/angular-cli/lib/bootstrap-local.js:30:14)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular-apollo-instagram-example@ start: `ng serve --port 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-apollo-instagram-example@ start script 'ng serve --port 3000'.
npm ERR! This is most likely a problem with the angular-apollo-instagram-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve --port 3000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-apollo-instagram-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular-apollo-instagram-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sorenbs/Downloads/angular-apollo-instagram-example-master/npm-debug.log
```

**Comment by schickling** [comment]
Can you try again with the newest version?

**Comment by marktani** [comment]
should be working: https://github.com/graphcool-examples/angular-apollo-instagram-example/commit/9540b0f15e53048821c6bfd7ba5fd0fc76588d72
