### ISSUE TITLE
Editing Permissions is broken

### ISSUE THREAD

**Issue by tfiwm** [graphcool/console#995]
When i try to edit permissions the 3rd Tab ("DEFINE RULES") is not working.
In the console you can see a javascript error:

```javascript
raven.min.js:2 Uncaught Error: Can only create NonNull of a Nullable GraphQLType but got: ID.
    at r (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:17:20818)
    at new e (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:11:95865)
    at r (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:39506)
    at https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:63:349160
    at Array.forEach (native)
    at https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:63:349095
    at Array.forEach (native)
    at i (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:63:349007)
    at Object.r [as default] (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:63:348809)
    at new a (https://console.graph.cool/app.cdd4e6b22f5302fa4bda.js:6:11057)
    at d._constructComponentWithoutOwner (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:472643)
    at d._constructComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:472510)
    at d.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:471692)
    at Object.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:122701)
    at h.mountChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502290)
    at h._createInitialChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:485153)
    at h.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:483291)
    at Object.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:122701)
    at h.mountChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502290)
    at h._createInitialChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:485153)
    at h.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:483291)
    at Object.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:122701)
    at h.mountChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502290)
    at h._createInitialChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:485153)
    at h.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:483291)
    at Object.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:122701)
    at h.mountChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502290)
    at h._createInitialChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:485153)
    at h.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:483291)
    at Object.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:122701)
    at d.performInitialMount (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:473465)
    at d.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:472351)
    at Object.mountComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:122701)
    at Object.updateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:469989)
    at h._reconcilerUpdateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502053)
    at h._updateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502802)
    at h.updateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502700)
    at h._updateDOMChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:487545)
    at h.updateComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:485751)
    at h.receiveComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:485304)
    at Object.receiveComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:123095)
    at Object.updateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:469870)
    at h._reconcilerUpdateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502053)
    at h._updateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502802)
    at h.updateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:502700)
    at h._updateDOMChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:487545)
    at h.updateComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:485751)
    at h.receiveComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:485304)
    at Object.receiveComponent (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:25:123095)
    at Object.updateChildren (https://console.graph.cool/vendor.cdd4e6b22f5302fa4bda.js:92:469870)
```

![image](https://cloud.githubusercontent.com/assets/988473/26356018/f7496dd6-3fca-11e7-8f23-4cd987c7bde5.png)
![image](https://cloud.githubusercontent.com/assets/988473/26356032/09f7a43e-3fcb-11e7-8baa-02804e853477.png)

**Comment by tfiwm** [comment]
Today everything works stable ;)

**Comment by timsuchanek** [comment]
Thanks for reporting @tfiwm and sorry for the trouble!
